[".config/oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh"
    refreshPeriod = "24h"

[".config/oh-my-zsh/custom/plugins/"]
    type = "git-repo"
    url = "https://github.com/zpm-zsh/ls"
    refreshPeriod = "24h"

[".zsh/zsh-autosuggestions/"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions"
    refreshPeriod = "24h"

[".zsh/zsh-autopair/"]
    type = "git-repo"
    url = "https://github.com/hlissner/zsh-autopair"
    refreshPeriod = "24h"

[".zsh/catppuccin-fzf/"]
    type = "git-repo"
    url = "https://github.com/catppuccin/fzf"
    refreshPeriod = "24h"

[".zsh/fzf-tab/"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab"
    refreshPeriod = "24h"

[".zsh/fzf-tab-source/"]
    type = "git-repo"
    url = "https://github.com/Freed-Wu/fzf-tab-source"
    refreshPeriod = "24h"

[".zsh/zsh-chezmoi/"]
    type = "git-repo"
    url = "https://github.com/mass8326/zsh-chezmoi"
    refreshPeriod = "24h"

[".config/btop/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/btop/archive/refs/heads/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/*"]
    refreshPeriod = "168h"

[".config/foot/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/foot/archive/refs/heads/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/*"]
    refreshPeriod = "168h"

[".config/kitty/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/kitty/archive/refs/heads/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/*"]
    refreshPeriod = "168h"

[".config/qt5ct/colors"]
    type = "archive"
    url = "https://github.com/catppuccin/qt5ct/archive/refs/heads/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/*"]
    refreshPeriod = "168h"

[".config/qt6ct/colors"]
    type = "archive"
    url = "https://github.com/catppuccin/qt5ct/archive/refs/heads/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/*"]
    refreshPeriod = "168h"

[".config/Kvantum"]
    type = "archive"
    url = "https://github.com/catppuccin/kvantum/archive/refs/heads/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/*"]
    refreshPeriod = "168h"

[".local/share/rofi/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/rofi/archive/refs/heads/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/*"]
    refreshPeriod = "168h"

[".config/zathura"]
    type = "archive"
    url = "https://github.com/catppuccin/zathura/archive/refs/heads/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/*"]
    refreshPeriod = "168h"

[".config/mako/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/mako/archive/refs/heads/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/**"]
    refreshPeriod = "168h"

[".config/ranger/colorschemes/catppuccin_latte.py"]
    type = "file"
    url = "https://github.com/dfrico/catppuccin-ranger/releases/latest/download/catppuccin_latte.py"
    refreshPeriod = "168h"

[".config/ranger/colorschemes/catppuccin_frappe.py"]
    type = "file"
    url = "https://github.com/dfrico/catppuccin-ranger/releases/latest/download/catppuccin_frappe.py"
    refreshPeriod = "168h"

[".config/ranger/colorschemes/catppuccin_macchiato.py"]
    type = "file"
    url = "https://github.com/dfrico/catppuccin-ranger/releases/latest/download/catppuccin_macchiato.py"
    refreshPeriod = "168h"

[".config/ranger/colorschemes/catppuccin_mocha.py"]
    type = "file"
    url = "https://github.com/dfrico/catppuccin-ranger/releases/latest/download/catppuccin_mocha.py"
    refreshPeriod = "168h"

[".config/spicetify/Themes/catppuccin"]
    type = "archive"
    url = "https://github.com/catppuccin/spicetify/archive/refs/heads/main.tar.gz"
    stripComponents = 2
    include = ["*/catppuccin/**"]
    refreshPeriod = "168h"

[".config/hypr"]
    type = "git-repo"
    url = "git@github.com:quantumfate/hypr.git"
    refreshPeriod = "24h"
